import React, { useState } from 'react'
import { Search, RefreshCw, Copy, Check, Flame, TrendingUp, FileText, Hash, Newspaper, ChevronDown, ChevronUp, BookOpen, ExternalLink, Clock, Sparkles, Volume2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { autoGeneratePostsWithGrok, regeneratePostWithFeedback, type AutoGeneratedPost } from '@/lib/api'
import { Slider } from '@/components/ui/slider'
import { cn } from '@/lib/utils'
import type { NewsResearchState, TrendingTopic } from '@/store/useContentStore'
import { useContentStore } from '@/store/useContentStore'

const SARAH_MINDMAP = `**Sarah Icelyn: Лор и Стратегия Продвижения** (полный текстовый майнд-мап)

**1. Личность и Биография (Лор)**  
├── **Происхождение**  
│   ├── Возраст: 27 лет (род. 20 ноября 1998)  
│   ├── Локация: Toledo, Ohio → Bloomfield Hills, Michigan (США)  
│   └── Корни: Ашкеназские евреи (мама, Польша) + польские (папа)  
├── **Психологический портрет**  
│   ├── Тип: Наблюдатель / Стратег (скрытый эмпат)  
│   ├── Травма: Эмоциональная пустота в семье (мать — только функции, отец отсутствовал)  
│   ├── Страх: Зависимость от других + потеря контроля  
│   ├── Конфликт: Рациональность против чувств  
│   ├── Ключевой страх: если открыться — останешься одна  
│   └── Главная формула персонажа: «Она продаёт ощущение близости, потому что больше всего боится в неё войти»  
└── **Внешность**  
    ├── Гетерохромия (левый глаз — голубой, правый — карий 💙🤎)  
    ├── Длинные чёрные волосы с густой прямой челкой и мягкими волнами до груди  
    ├── Фигура: песочные часы 34-25-37, рост 168 см  
    └── Стиль: минимализм и элегантность (тёмные нейтральные цвета, безупречная опрятность)

**2. Профессиональный Образ (РД)**  
├── **Роль: Дворецкий (Butler) в люксовом отеле / VIP-сервис**  
│   ├── Локация: 5★-отель, частный люкс, апартаменты, VIP-этаж  
│   ├── Атрибуты: идеально сидящая форма, белые перчатки, безупречная выправка  
│   └── Суть: персонализированная забота через строгую дистанцию (помнит предпочтения гостей, создаёт ощущение исключительности)  
└── **Границы сервиса**  
    ├── Без личных встреч  
    ├── Нет видеозвонков и голосовых звонков  
    └── Только иллюзия исключительности и заботы

**3. Маркетинговая Стратегия (OFM)**  
├── **Формула Виральности**  
│   ├── Рабочий референс (трендовый формат, который уже набрал миллионы)  
│   ├── Локация ГЕО (только США: Мичиган, американские спальни, гаражи, люксовые отели, флаги США)  
│   ├── Уникальные черты персонажа (гетерохромия, стиль дворецкого, ЛОР)  
│   └── Триггерная тема (Red Flags в отношениях, психология «холодной» девушки, контраст униформы и домашнего уюта)  
└── **Принципы Контента**  
    ├── Стабильность визуала (единый цветокор, стиль, локации)  
    ├── Запрет на прыжки по нишам (только «Люкс-дворецкий» или «Соседка из Мичигана»)  
    ├── Математический перебор комбинаций (меняем только одну переменную)  
    └── Масштабирование успешных связок (один удачный формат → 5–10 роликов)

**4. Интересы и Привычки**  
├── **Вкусы**  
│   ├── Еда: суши, итальянская паста (карбонара), ночная пицца в 2 часа ночи, клубника в шоколаде, шампанское к десертам  
│   ├── Музыка: The Weeknd, медленный R&B, сексуальная поп (Doja Cat, Ariana Grande)  
│   └── Кино/сериалы: Bridgerton, 365 дней, романтические комедии и драмы  
├── **Стиль общения**  
│   ├── Игривый и кокетливый, но всегда сдержанный и элегантный  
│   ├── Короткие предложения  
│   └── Много комплиментов, вопросов к аудитории и лёгких поддразниваний  
└── **Питомец**: мини-пиг по имени Reaper

**Дополнительно из полного ЛОРа (арки и конфликты)**  
- Конфликты: контроль vs близость, образ vs реальность, забота о других vs отказ заботиться о себе  
- Арка роста: научиться принимать тепло, не теряя контроля  
- Арка стагнации: оставаться идеальной и недосягаемой  
- Теневая арка: эмоциональное истощение от вечного контроля`

interface NewsToPostPanelProps {
  research: NewsResearchState | null
  isResearching: boolean
  awaitingTopicSelection: boolean
  onResearch: () => void
  onSelectTopic: (topic: TrendingTopic) => void
  onRegenerate: () => void
  onRegenerateWithEmotion: (emotion: string) => void
  onCompress: (targetPercent: number) => void
  onResizeBySentences: (targetSentences: number) => void
  onPostTextChange: (text: string) => void
  onDurationChange: (duration: number) => void
}

interface AutoGenerateSettings {
  postCount: number
  minSentences: number
  maxSentences: number
}

function renderTextWithLinks(text: string) {
  // Match [[n]](url) OR [text](url) — handles both single and double bracket citation formats
  const linkRegex = /\[(\[[^\]]*\]|[^\]]+)\]\((https?:\/\/[^\s)]+)\)/g
  const parts: React.ReactNode[] = []
  let lastIndex = 0
  let match: RegExpExecArray | null

  while ((match = linkRegex.exec(text)) !== null) {
    if (match.index > lastIndex) {
      parts.push(text.slice(lastIndex, match.index))
    }
    parts.push(
      <a
        key={match.index}
        href={match[2]}
        target="_blank"
        rel="noopener noreferrer"
        className="text-primary hover:text-primary/80 underline underline-offset-2 break-all transition-colors"
      >
        {match[1]}
      </a>
    )
    lastIndex = match.index + match[0].length
  }

  if (lastIndex < text.length) {
    parts.push(text.slice(lastIndex))
  }

  return parts.length > 1 ? parts : text
}

function CopyButton({ text, label }: { text: string; label: string }) {
  const [copied, setCopied] = useState(false)

  const handleCopy = async () => {
    await navigator.clipboard.writeText(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <button
      onClick={handleCopy}
      className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-md bg-secondary/50 hover:bg-secondary border border-border text-xs font-medium text-foreground transition-colors"
    >
      {copied ? <Check className="h-3 w-3 text-emerald-400" /> : <Copy className="h-3 w-3" />}
      {copied ? 'Скопировано!' : label}
    </button>
  )
}

function EngagementBadge({ level }: { level: TrendingTopic['engagement'] }) {
  return (
    <span
      className={cn(
        'text-[10px] font-bold px-1.5 py-0.5 rounded-full uppercase tracking-wide',
        level === 'high' ? 'bg-red-500/15 text-red-400' :
        level === 'medium' ? 'bg-amber-500/15 text-amber-400' :
        'bg-slate-500/15 text-slate-400'
      )}
    >
      {level === 'high' ? '🔥 High' : level === 'medium' ? '⚡ Med' : '· Low'}
    </span>
  )
}

export function NewsToPostPanel({
  research,
  isResearching,
  awaitingTopicSelection,
  onResearch,
  onSelectTopic,
  onRegenerate,
  onRegenerateWithEmotion,
  onCompress,
  onResizeBySentences,
  onPostTextChange,
  onDurationChange,
}: NewsToPostPanelProps) {
  const { apiKeys, addLog, setPendingVoiceText, setActiveTab } = useContentStore()
  const [detailsOpen, setDetailsOpen] = useState(false)
  const [showMindmap, setShowMindmap] = useState(false)
  const [compressionLevel, setCompressionLevel] = useState(100)
  const [targetSentences, setTargetSentences] = useState<number | ''>(5)
  const [selectedEmotion, setSelectedEmotion] = useState<string | null>(null)
  const [selectedNewsDetail, setSelectedNewsDetail] = useState<{
    title: string
    translationRu: string
    sources: string[]
  } | null>(null)
  const [showAutoGenerateDialog, setShowAutoGenerateDialog] = useState(false)
  const [autoGenerateSettings, setAutoGenerateSettings] = useState<AutoGenerateSettings>({
    postCount: 5,
    minSentences: 3,
    maxSentences: 7,
  })
  const [isAutoGenerating, setIsAutoGenerating] = useState(false)
  const [autoGeneratedPosts, setAutoGeneratedPosts] = useState<AutoGeneratedPost[]>([])
  const [postLanguages, setPostLanguages] = useState<Record<number, 'en' | 'ru'>>({})
  const [postFeedback, setPostFeedback] = useState<Record<number, string>>({})
  const [regeneratingPosts, setRegeneratingPosts] = useState<Record<number, boolean>>({})
  
  const togglePostLanguage = (index: number) => {
    setPostLanguages(prev => ({
      ...prev,
      [index]: prev[index] === 'ru' ? 'en' : 'ru'
    }))
  }

  const handleRegeneratePost = async (index: number) => {
    const feedback = postFeedback[index]?.trim()
    if (!feedback) {
      addLog('⚠️ Введите пожелания для редактирования', 'error')
      return
    }

    if (!apiKeys.grok) {
      addLog('⚠️ Не указан Grok API ключ', 'error')
      return
    }

    setRegeneratingPosts(prev => ({ ...prev, [index]: true }))

    try {
      const currentPost = autoGeneratedPosts[index]
      const result = await regeneratePostWithFeedback(
        apiKeys.grok,
        currentPost,
        feedback,
        addLog
      )

      // Update the post with new texts
      const updatedPosts = [...autoGeneratedPosts]
      updatedPosts[index] = {
        ...currentPost,
        postText: result.postText,
        postTextRu: result.postTextRu
      }
      setAutoGeneratedPosts(updatedPosts)

      // Clear feedback after successful regeneration
      setPostFeedback(prev => ({ ...prev, [index]: '' }))
      addLog(`✅ Пост #${index + 1} перегенерирован`, 'success')
    } catch (err) {
      addLog(`❌ Ошибка регенерации: ${err instanceof Error ? err.message : 'Unknown'}`, 'error')
    } finally {
      setRegeneratingPosts(prev => ({ ...prev, [index]: false }))
    }
  }

  const handleVoicePost = (index: number) => {
    const currentPost = autoGeneratedPosts[index]
    const textToVoice = postLanguages[index] === 'ru' ? currentPost.postTextRu : currentPost.postText
    setPendingVoiceText(textToVoice)
    setActiveTab('voice')
    addLog(`🎤 Текст поста #${index + 1} отправлен на озвучку`, 'info')
  }

  const handleVoiceResearchPost = () => {
    if (research?.postText) {
      setPendingVoiceText(research.postText)
      setActiveTab('voice')
      addLog('🎤 Текст поста отправлен на озвучку', 'info')
    }
  }

  const handleAutoGenerate = async () => {
    if (!apiKeys.grok) {
      addLog('⚠️ Не указан Grok API ключ', 'error')
      return
    }

    setShowAutoGenerateDialog(false)
    setIsAutoGenerating(true)
    setAutoGeneratedPosts([])
    setPostLanguages({})

    try {
      const posts = await autoGeneratePostsWithGrok(
        apiKeys.grok,
        autoGenerateSettings.postCount,
        autoGenerateSettings.minSentences,
        autoGenerateSettings.maxSentences,
        addLog
      )
      
      setAutoGeneratedPosts(posts)
      addLog(`✅ Сгенерировано ${posts.length} постов`, 'success')
    } catch (err) {
      addLog(`❌ Ошибка автогенерации: ${err instanceof Error ? err.message : 'Unknown'}`, 'error')
    } finally {
      setIsAutoGenerating(false)
    }
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <div className="flex items-center gap-2 mb-1">
          <Newspaper className="h-4 w-4 text-primary" />
          <h1 className="text-lg font-semibold text-foreground">News to Post</h1>
        </div>
        <p className="text-sm text-muted-foreground">
          Автоматический мониторинг горячих новостей США + генерация провокационного поста
        </p>
      </div>

      {/* Persona card */}
      <div className="rounded-xl border border-primary/20 bg-primary/5 p-4">
        <div className="flex items-start gap-3">
          <div className="h-9 w-9 rounded-lg bg-primary/10 flex items-center justify-center shrink-0">
            <span className="text-base">💙🤎</span>
          </div>
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2 mb-0.5">
              <span className="text-xs px-2 py-0.5 rounded-full bg-primary/10 text-primary font-medium">Активирован</span>
            </div>
            <p className="text-xs text-muted-foreground leading-relaxed">
              27 лет · Bloomfield Hills, Michigan · Холодная, элегантная, провокационная · Дворецкий в люкс-отеле
            </p>
          </div>
          <button
            onClick={() => setShowMindmap(true)}
            className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-md bg-primary/10 hover:bg-primary/20 border border-primary/30 text-xs font-medium text-primary transition-colors shrink-0"
          >
            <BookOpen className="h-3 w-3" />
            Майнд-мап
          </button>
        </div>
      </div>

      {/* Duration Slider */}
      <div className="rounded-xl border border-border bg-card p-4 space-y-3">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Clock className="h-4 w-4 text-muted-foreground" />
            <label className="text-sm font-medium text-foreground">Длительность поста</label>
          </div>
          <span className="text-xs font-semibold px-2 py-0.5 rounded-full bg-primary/10 text-primary">
            {research?.postDuration ?? 30} сек
          </span>
        </div>
        <Slider
          min={5}
          max={60}
          step={5}
          value={[research?.postDuration ?? 30]}
          onValueChange={([v]) => onDurationChange(v)}
          className="w-full"
        />
        <div className="flex justify-between text-[10px] text-muted-foreground/60">
          <span>5 сек (короткий)</span>
          <span>30 сек (средний)</span>
          <span>60 сек (длинный)</span>
        </div>
        <p className="text-xs text-muted-foreground">
          {research?.postDuration && research.postDuration <= 15 ? '📱 50-80 слов - быстрый TikTok' :
           research?.postDuration && research.postDuration <= 30 ? '⚡ 100-150 слов - стандарт Instagram' :
           '📖 180-250 слов - развёрнутый пост'}
        </p>
      </div>

      {/* Research buttons */}
      {!research && (
        <div className="flex gap-3">
          <Button
            onClick={onResearch}
            disabled={isResearching}
            className="flex-1 h-12 text-base font-semibold gap-2 bg-primary hover:bg-primary/90 shadow-lg shadow-primary/20"
            size="lg"
          >
            {isResearching ? (
              <>
                <RefreshCw className="h-4 w-4 animate-spin" />
                Анализирую тренды...
              </>
            ) : (
              <>
                <Search className="h-4 w-4" />
                Провести ресерч новостей
              </>
            )}
          </Button>
          <Button
            onClick={() => setShowAutoGenerateDialog(true)}
            disabled={isResearching}
            variant="outline"
            className="h-12 px-4 gap-2 border-primary/30 hover:bg-primary/10"
            size="lg"
          >
            <Sparkles className="h-4 w-4" />
            <span className="hidden sm:inline">Автоматически написать посты</span>
            <span className="sm:hidden">Авто-генерация</span>
          </Button>
        </div>
      )}

      {/* Researching progress */}
      {isResearching && (
        <div className="rounded-xl border border-primary/20 bg-primary/5 px-4 py-3 flex items-center justify-between gap-3">
          <div className="flex items-center gap-2 text-sm font-medium text-foreground min-w-0">
            <RefreshCw className="h-4 w-4 animate-spin text-primary shrink-0" />
            <span className="truncate">
              {awaitingTopicSelection
                ? 'Ищу тренды...'
                : research?.currentStep || 'Анализирую выбранную тему...'}
            </span>
          </div>
          {research?.stepLogs && research.stepLogs.length > 0 && (() => {
            const last = research.stepLogs[research.stepLogs.length - 1]
            const preview = last.result.length > 55 ? last.result.slice(0, 55) + '…' : last.result
            return (
              <div className="flex items-center gap-1.5 shrink-0 max-w-[45%]">
                <Check className="h-3 w-3 text-emerald-400 shrink-0" />
                <span className="text-xs text-muted-foreground truncate" title={last.result}>
                  <span className="text-emerald-400/70 font-medium">{last.step}:</span>{' '}{preview}
                </span>
              </div>
            )
          })()}
        </div>
      )}

      {/* Topic selection — awaiting user pick */}
      {awaitingTopicSelection && research && research.trending.length > 0 && (
        <div className="rounded-xl border border-primary/30 bg-card overflow-hidden">
          <div className="px-4 py-3 border-b border-primary/20 bg-primary/5 flex items-center gap-2">
            <Flame className="h-4 w-4 text-primary" />
            <span className="text-sm font-bold text-foreground">Выберите тему для ресерча</span>
            <span className="text-xs text-muted-foreground ml-auto">{research.trending.length} темы найдены</span>
          </div>
          <div className="divide-y divide-border/50">
            {research.trending.map((topic, i) => (
              <div
                key={i}
                className="px-4 py-4 hover:bg-secondary/30 transition-colors group cursor-pointer"
                onClick={() => onSelectTopic(topic)}
              >
                <div className="flex items-start gap-3">
                  <div className="flex-1 space-y-1 min-w-0">
                    <div className="flex items-center gap-2 flex-wrap">
                      <span className="text-xs font-bold text-muted-foreground/60">#{i + 1}</span>
                      <EngagementBadge level={topic.engagement} />
                    </div>
                    <p className="text-sm font-semibold text-foreground leading-snug">
                      {topic.titleRu || topic.title}
                    </p>
                    <p className="text-[11px] text-muted-foreground/60 italic leading-snug">{topic.title}</p>
                    <p className="text-xs text-muted-foreground leading-relaxed">
                      {topic.summaryRu || topic.summary}
                    </p>
                    {topic.polarization && (
                      <p className="text-xs text-amber-400/80 italic">⚡ {topic.polarization}</p>
                    )}
                    {topic.metrics && (
                      <div className="flex flex-wrap items-center gap-2 pt-1">
                        {topic.metrics.postCount && (
                          <span className="inline-flex items-center gap-1 rounded-md bg-secondary/60 px-2 py-0.5 text-[11px] font-medium text-muted-foreground">
                            <span className="text-primary/70">✦</span>{topic.metrics.postCount}
                          </span>
                        )}
                        {topic.metrics.topEngagement && (
                          <span className="inline-flex items-center gap-1 rounded-md bg-secondary/60 px-2 py-0.5 text-[11px] font-medium text-muted-foreground">
                            <span className="text-emerald-400/70">↑</span>{topic.metrics.topEngagement}
                          </span>
                        )}
                        {topic.metrics.trendSince && (
                          <span className="inline-flex items-center gap-1 rounded-md bg-secondary/60 px-2 py-0.5 text-[11px] font-medium text-muted-foreground">
                            <Clock className="h-2.5 w-2.5 text-muted-foreground/60" />{topic.metrics.trendSince}
                          </span>
                        )}
                      </div>
                    )}
                  </div>
                  <button
                    onClick={(e) => { e.stopPropagation(); onSelectTopic(topic) }}
                    className="shrink-0 px-3 py-1.5 rounded-lg bg-primary/10 hover:bg-primary/20 border border-primary/30 text-xs font-semibold text-primary transition-colors opacity-0 group-hover:opacity-100"
                  >
                    Выбрать →
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Results — shown after topic is selected (not during selection phase) */}
      {research && !awaitingTopicSelection && (
        <div className="space-y-5">
          {/* Timestamp + New Research — only after completion */}
          {!isResearching && research.researchedAt && (
            <div className="flex items-center justify-between">
              <span className="text-xs text-muted-foreground">Ресерч выполнен в {research.researchedAt}</span>
              <button
                onClick={onResearch}
                className="flex items-center gap-1.5 text-xs text-primary hover:text-primary/80 transition-colors font-medium"
              >
                <Search className="h-3 w-3" />
                Новый ресерч
              </button>
            </div>
          )}

          {/* Top 5 Trending */}
          {research.trending.length > 0 && (
            <div className="rounded-xl border border-border bg-card overflow-hidden">
              <div className="px-4 py-3 border-b border-border/50 flex items-center gap-2">
                <TrendingUp className="h-4 w-4 text-primary" />
                <span className="text-sm font-semibold text-foreground">Топ трендов США</span>
                <span className="text-xs text-muted-foreground">({research.trending.length} найдено)</span>
              </div>
              <div className="divide-y divide-border/50">
                {research.trending.map((topic, i) => {
                  const isSelected = topic.title === research.selectedTopic.title
                  return (
                    <div
                      key={i}
                      className={cn(
                        'px-4 py-3 space-y-1 transition-colors',
                        isSelected ? 'bg-primary/5 border-l-2 border-l-primary' : ''
                      )}
                    >
                      <div className="flex items-start justify-between gap-2">
                        <div className="flex items-start gap-3">
                          {isSelected && <Flame className="h-3.5 w-3.5 text-red-400 shrink-0" />}
                          <div className="min-w-0">
                            <span className={cn(
                              'text-sm font-medium block',
                              isSelected ? 'text-foreground' : 'text-foreground/80'
                            )}>
                              {topic.titleRu || topic.title}
                            </span>
                            {topic.titleRu && <span className="text-[11px] text-muted-foreground/50 italic">{topic.title}</span>}
                          </div>
                        </div>
                        <EngagementBadge level={topic.engagement} />
                      </div>
                      <p className="text-xs text-muted-foreground leading-relaxed line-clamp-2">{topic.summary}</p>
                      {isSelected && (
                        <div className="flex items-center gap-1.5 mt-1">
                          <span className="text-[10px] font-semibold text-primary uppercase tracking-wide">Выбрана ✓</span>
                          <span className="text-[10px] text-muted-foreground">— {topic.polarization}</span>
                        </div>
                      )}
                    </div>
                  )
                })}
              </div>
            </div>
          )}

          {/* Selected Topic Detail */}
          {research.selectedTopic.title && (
          <div className="rounded-xl border border-amber-500/30 bg-amber-500/5 p-4 space-y-2">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Flame className="h-4 w-4 text-amber-400" />
                <span className="text-sm font-semibold text-foreground">Выбранная тема</span>
                <EngagementBadge level={research.selectedTopic.engagement} />
              </div>
              <button
                onClick={() => setSelectedNewsDetail({
                  title: research.selectedTopic.title,
                  translationRu: research.translationRu,
                  sources: research.sources,
                })}
                className="flex items-center gap-1 text-xs text-amber-400 hover:text-amber-300 transition-colors font-medium"
              >
                <ExternalLink className="h-3 w-3" />
                Подробнее
              </button>
            </div>
            <p className="text-sm font-medium text-foreground">{research.selectedTopic.titleRu || research.selectedTopic.title}</p>
            {research.selectedTopic.titleRu && <p className="text-[11px] text-muted-foreground/50 italic">{research.selectedTopic.title}</p>}
            <p className="text-xs text-muted-foreground leading-relaxed">{research.selectedTopic.summary}</p>
            <p className="text-xs text-amber-400/80 italic">⚡ {research.selectedTopic.polarization}</p>
            {research.selectedTopic.metrics && (
              <div className="flex flex-wrap items-center gap-2 pt-1">
                {research.selectedTopic.metrics.postCount && (
                  <span className="inline-flex items-center gap-1 rounded-md bg-amber-500/10 px-2 py-0.5 text-[11px] font-medium text-amber-400/80">
                    <span className="text-amber-400/60">✦</span>{research.selectedTopic.metrics.postCount}
                  </span>
                )}
                {research.selectedTopic.metrics.topEngagement && (
                  <span className="inline-flex items-center gap-1 rounded-md bg-amber-500/10 px-2 py-0.5 text-[11px] font-medium text-amber-400/80">
                    <span className="text-emerald-400/70">↑</span>{research.selectedTopic.metrics.topEngagement}
                  </span>
                )}
                {research.selectedTopic.metrics.trendSince && (
                  <span className="inline-flex items-center gap-1 rounded-md bg-amber-500/10 px-2 py-0.5 text-[11px] font-medium text-amber-400/80">
                    <Clock className="h-2.5 w-2.5" />{research.selectedTopic.metrics.trendSince}
                  </span>
                )}
              </div>
            )}
          </div>
          )}

          {/* X (Twitter) Posts */}
          {research.xPosts && research.xPosts.length > 0 && (
            <div className="rounded-xl border border-border bg-card overflow-hidden">
              <div className="px-4 py-3 border-b border-border/50 flex items-center gap-2">
                <span className="text-sm font-bold text-foreground leading-none">𝕏</span>
                <span className="text-sm font-semibold text-foreground">Посты из X (Twitter)</span>
                <span className="text-xs text-muted-foreground">({research.xPosts.length} постов)</span>
              </div>
              <div className="divide-y divide-border/50">
                {research.xPosts.map((post, i) => (
                  <div key={i} className="px-4 py-3 space-y-2 hover:bg-secondary/20 transition-colors group">
                    <div className="flex items-start justify-between gap-2">
                      <div className="flex items-center gap-2 min-w-0">
                        <div className="h-7 w-7 rounded-full bg-primary/10 border border-primary/20 flex items-center justify-center shrink-0">
                          <span className="text-[10px] font-bold text-primary">
                            {post.author?.charAt(0)?.toUpperCase() ?? '?'}
                          </span>
                        </div>
                        <div className="min-w-0">
                          <span className="text-xs font-semibold text-foreground truncate block">{post.author}</span>
                          <span className="text-[10px] text-muted-foreground">{post.handle}</span>
                        </div>
                      </div>
                      <div className="flex items-center gap-2 shrink-0">
                        {post.engagement && (
                          <span className="text-[10px] text-muted-foreground/70 font-medium">{post.engagement}</span>
                        )}
                        {post.url && (
                          <a
                            href={post.url}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="opacity-0 group-hover:opacity-100 transition-opacity"
                          >
                            <ExternalLink className="h-3 w-3 text-primary" />
                          </a>
                        )}
                      </div>
                    </div>
                    <p className="text-xs text-foreground/90 leading-relaxed">
                      {post.url ? (
                        <a
                          href={post.url}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="hover:text-primary transition-colors"
                        >
                          {post.text}
                        </a>
                      ) : post.text}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* News Details (collapsible) */}
          {research.newsDetails && (
          <div className="rounded-xl border border-border bg-card overflow-hidden">
            <button
              onClick={() => setDetailsOpen(!detailsOpen)}
              className="w-full px-4 py-3 flex items-center justify-between text-left hover:bg-secondary/30 transition-colors"
            >
              <div className="flex items-center gap-2">
                <FileText className="h-4 w-4 text-muted-foreground" />
                <span className="text-sm font-medium text-foreground">Детали новости</span>
              </div>
              {detailsOpen ? (
                <ChevronUp className="h-3.5 w-3.5 text-muted-foreground" />
              ) : (
                <ChevronDown className="h-3.5 w-3.5 text-muted-foreground" />
              )}
            </button>
            {detailsOpen && (
              <div className="px-4 pb-4 border-t border-border/50">
                <p className="text-xs text-muted-foreground leading-relaxed whitespace-pre-line pt-3">
                  {renderTextWithLinks(research.newsDetails)}
                </p>
              </div>
            )}
          </div>
          )}

          {/* Generated Post — only show when post exists */}
          {research.postText && (
          <div className="rounded-xl border border-border bg-card overflow-hidden">
            <div className="px-4 py-3 border-b border-border/50 flex items-center justify-between">
              <div className="flex items-center gap-2">
                <FileText className="h-4 w-4 text-primary" />
                <span className="text-sm font-semibold text-foreground">Сгенерированный пост</span>
              </div>
              <div className="flex items-center gap-2">
                <CopyButton text={research.postText} label="Копировать" />
                <Button
                  onClick={handleVoiceResearchPost}
                  variant="outline"
                  size="sm"
                  className="h-7 text-xs gap-1.5"
                >
                  <Volume2 className="h-3 w-3" />
                  Озвучить
                </Button>
              </div>
            </div>
            {/* Emotion picker */}
            <div className="px-4 pt-3 pb-1 border-b border-border/30">
              <p className="text-[11px] text-muted-foreground/60 mb-2 font-medium uppercase tracking-wide">Тон перегенерации:</p>
              <div className="flex flex-wrap gap-1.5">
                {([
                  { emoji: '❄️', label: 'Холодная', value: 'cold and detached, almost icy' },
                  { emoji: '😏', label: 'Ироничная', value: 'deeply ironic and dry' },
                  { emoji: '🔥', label: 'Злая', value: 'fierce and ruthless' },
                  { emoji: '💅', label: 'Снисходительная', value: 'condescending and superior' },
                  { emoji: '😢', label: 'Меланхоличная', value: 'melancholic and reflective' },
                  { emoji: '😈', label: 'Саркастичная', value: 'deeply sarcastic and cutting' },
                  { emoji: '💘', label: 'Соблазнительная', value: 'seductive and teasing' },
                ] as const).map(({ emoji, label, value }) => (
                  <button
                    key={value}
                    onClick={() => setSelectedEmotion(selectedEmotion === value ? null : value)}
                    className={cn(
                      'flex items-center gap-1 px-2 py-1 rounded-lg border text-xs font-medium transition-colors',
                      selectedEmotion === value
                        ? 'bg-primary/20 border-primary/50 text-primary'
                        : 'bg-secondary/40 border-border/50 text-muted-foreground hover:text-foreground hover:bg-secondary/70'
                    )}
                  >
                    <span>{emoji}</span>{label}
                  </button>
                ))}
                {selectedEmotion && (
                  <button
                    onClick={() => {
                      onRegenerateWithEmotion(selectedEmotion)
                      setSelectedEmotion(null)
                    }}
                    disabled={isResearching}
                    className="flex items-center gap-1.5 px-3 py-1 rounded-lg bg-primary text-primary-foreground text-xs font-semibold hover:bg-primary/80 transition-colors disabled:opacity-50"
                  >
                    {isResearching ? <RefreshCw className="h-3 w-3 animate-spin" /> : <span>↺</span>}
                    Перегенерировать
                  </button>
                )}
              </div>
            </div>
            <div className="p-4 space-y-4">
              <textarea
                value={research.postText}
                onChange={(e) => onPostTextChange(e.target.value)}
                className="w-full min-h-[200px] bg-transparent text-sm text-foreground leading-relaxed resize-none focus:outline-none"
                placeholder="Пост будет сгенерирован после ресерча..."
              />
              {/* Text stats */}
              <div className="flex items-center gap-3 text-[11px] text-muted-foreground/60 border-t border-border/30 pt-2">
                <span><span className="font-semibold text-muted-foreground">{research.postText.length}</span> симв.</span>
                <span className="text-border/60">·</span>
                <span><span className="font-semibold text-muted-foreground">{research.postText.trim().split(/\s+/).filter(w => w.length > 0).length}</span> слов</span>
                <span className="text-border/60">·</span>
                <span><span className="font-semibold text-muted-foreground">{research.postText.split(/[.!?]+/).filter(s => s.trim().length > 0).length}</span> предл.</span>
              </div>
              {/* Resize controls */}
              <div className="border-t border-border/50 pt-3 space-y-3">
                {/* Percentage slider */}
                <div className="space-y-2">
                  <div className="flex items-center justify-between gap-3">
                    <div className="flex items-center gap-2 min-w-0">
                      <span className="text-xs text-muted-foreground shrink-0">Объём текста:</span>
                      <span className={cn(
                        'text-xs font-bold tabular-nums shrink-0',
                        compressionLevel === 100 ? 'text-muted-foreground' :
                        compressionLevel > 100 ? 'text-emerald-400' :
                        compressionLevel >= 60 ? 'text-amber-400' : 'text-red-400'
                      )}>{compressionLevel}%</span>
                      <span className="text-[10px] text-muted-foreground/50 shrink-0">
                        {compressionLevel === 100 ? '(без изменений)' :
                          compressionLevel > 100 ? `(расширить на ${compressionLevel - 100}%)` :
                          `(сократить на ${100 - compressionLevel}%)`}
                      </span>
                    </div>
                    <button
                      onClick={() => onCompress(compressionLevel)}
                      disabled={isResearching || compressionLevel === 100}
                      className={cn(
                        'shrink-0 flex items-center gap-1.5 px-3 py-1.5 rounded-lg border text-xs font-semibold transition-colors disabled:opacity-40 disabled:cursor-not-allowed',
                        compressionLevel > 100
                          ? 'bg-emerald-500/10 hover:bg-emerald-500/20 border-emerald-500/30 text-emerald-400'
                          : 'bg-primary/10 hover:bg-primary/20 border-primary/30 text-primary'
                      )}
                    >
                      {isResearching ? <RefreshCw className="h-3 w-3 animate-spin" /> :
                        compressionLevel > 100 ? <span>↑</span> : <span>✂</span>}
                      {compressionLevel > 100 ? 'Расширить текст' : 'Сократить текст'}
                    </button>
                  </div>
                  <Slider
                    value={[compressionLevel]}
                    onValueChange={([v]) => setCompressionLevel(v)}
                    min={20}
                    max={200}
                    step={5}
                    className="w-full"
                  />
                  <div className="flex justify-between text-[10px] text-muted-foreground/50">
                    <span>20% (минимум)</span>
                    <span>100% (исходный)</span>
                    <span>200% (×2)</span>
                  </div>
                </div>
                {/* Sentences input */}
                <div className="flex items-center gap-2 border-t border-border/30 pt-2">
                  <span className="text-xs text-muted-foreground shrink-0">Точно предложений:</span>
                  <input
                    type="number"
                    min={1}
                    max={30}
                    value={targetSentences}
                    onChange={(e) => setTargetSentences(e.target.value === '' ? '' : Math.max(1, Math.min(30, Number(e.target.value))))}
                    className="w-16 bg-secondary/40 border border-border/50 rounded-md px-2 py-1 text-xs text-foreground text-center focus:outline-none focus:border-primary/50 tabular-nums"
                  />
                  <span className="text-[10px] text-muted-foreground/40">
                    сейчас: {research.postText.split(/[.!?]+/).filter(s => s.trim().length > 0).length}
                  </span>
                  <button
                    onClick={() => typeof targetSentences === 'number' && onResizeBySentences(targetSentences)}
                    disabled={isResearching || targetSentences === ''}
                    className="ml-auto shrink-0 flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-secondary/60 hover:bg-secondary border border-border/50 text-xs font-semibold text-foreground transition-colors disabled:opacity-40 disabled:cursor-not-allowed"
                  >
                    {isResearching ? <RefreshCw className="h-3 w-3 animate-spin" /> : <span>✏</span>}
                    Пересчитать
                  </button>
                </div>
              </div>
            </div>
          </div>
          )}

          {/* Post Translation (Russian) */}
          {research.postTranslationRu && (
            <div className="rounded-xl border border-border bg-card overflow-hidden">
              <div className="px-4 py-3 border-b border-border/50 flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <span className="text-base">🇷🇺</span>
                  <span className="text-sm font-semibold text-foreground">Перевод поста</span>
                </div>
                <CopyButton text={research.postTranslationRu} label="Копировать" />
              </div>
              <div className="p-4">
                <p className="text-sm text-muted-foreground leading-relaxed whitespace-pre-line">
                  {research.postTranslationRu}
                </p>
              </div>
            </div>
          )}

          {/* Hashtags */}
          {research.hashtags.length > 0 && (
            <div className="rounded-xl border border-border bg-card p-4 space-y-3">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <Hash className="h-4 w-4 text-primary" />
                  <span className="text-sm font-semibold text-foreground">Хештеги</span>
                </div>
                <CopyButton text={research.hashtags.join(' ')} label="Копировать все" />
              </div>
              <div className="flex flex-wrap gap-2">
                {research.hashtags.map((tag, i) => (
                  <span
                    key={i}
                    className="text-xs font-medium px-2.5 py-1 rounded-full bg-primary/10 text-primary border border-primary/20"
                  >
                    {tag}
                  </span>
                ))}
              </div>
            </div>
          )}

          {/* Action buttons */}
          <div className="flex gap-3">
            <Button
              onClick={onRegenerate}
              disabled={isResearching}
              variant="outline"
              className="flex-1 gap-2"
            >
              {isResearching ? (
                <>
                  <RefreshCw className="h-4 w-4 animate-spin" />
                  Генерирую...
                </>
              ) : (
                <>
                  <RefreshCw className="h-4 w-4" />
                  Перегенерировать пост
                </>
              )}
            </Button>
            <Button
              onClick={onResearch}
              disabled={isResearching}
              className="flex-1 gap-2 bg-primary hover:bg-primary/90"
            >
              <Search className="h-4 w-4" />
              Новый ресерч
            </Button>
          </div>
        </div>
      )}

      {/* Mindmap Dialog */}
      <Dialog open={showMindmap} onOpenChange={setShowMindmap}>
        <DialogContent className="max-w-4xl max-h-[85vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <BookOpen className="h-5 w-5 text-primary" />
              Sarah Icelyn — Полная Майнд-Мап
            </DialogTitle>
          </DialogHeader>
          <div className="prose prose-sm dark:prose-invert max-w-none">
            <pre className="whitespace-pre-wrap text-xs leading-relaxed font-mono bg-secondary/30 p-4 rounded-lg">
{SARAH_MINDMAP}
            </pre>
          </div>
        </DialogContent>
      </Dialog>

      {/* News Detail Dialog */}
      <Dialog open={!!selectedNewsDetail} onOpenChange={() => setSelectedNewsDetail(null)}>
        <DialogContent className="max-w-3xl max-h-[85vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="text-base leading-snug pr-6">
              {selectedNewsDetail?.title}
            </DialogTitle>
          </DialogHeader>
          <div className="space-y-4">
            {/* Russian Translation */}
            {selectedNewsDetail?.translationRu && (
              <div className="space-y-2">
                <div className="flex items-center gap-2">
                  <span className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">🇷🇺 Перевод на русский</span>
                </div>
                <div className="text-sm text-foreground leading-relaxed bg-secondary/30 p-3 rounded-lg space-y-2">
                  {selectedNewsDetail.translationRu.split('\n').map((line, i) => (
                    <p key={i}>{renderTextWithLinks(line)}</p>
                  ))}
                </div>
              </div>
            )}

            {/* Sources */}
            {selectedNewsDetail?.sources && selectedNewsDetail.sources.length > 0 && (
              <div className="space-y-2">
                <div className="flex items-center gap-2">
                  <ExternalLink className="h-3.5 w-3.5 text-muted-foreground" />
                  <span className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">Источники</span>
                </div>
                <div className="space-y-1.5">
                  {selectedNewsDetail.sources.map((source, i) => {
                    const isTweet = source.includes('x.com') || source.includes('twitter.com')
                    let label = source
                    try { label = new URL(source).hostname.replace('www.', '') } catch { /* use raw */ }
                    return (
                      <a
                        key={i}
                        href={source}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="flex items-center gap-2 text-xs text-primary hover:text-primary/80 transition-colors group"
                      >
                        {isTweet
                          ? <span className="shrink-0 text-[11px] font-bold leading-none">𝕏</span>
                          : <ExternalLink className="h-3 w-3 shrink-0" />
                        }
                        <span className="truncate group-hover:underline">{label}</span>
                      </a>
                    )
                  })}
                </div>
              </div>
            )}

            {(!selectedNewsDetail?.sources || selectedNewsDetail.sources.length === 0) && (
              <div className="text-xs text-muted-foreground italic">
                Источники не найдены
              </div>
            )}
          </div>
        </DialogContent>
      </Dialog>

      {/* Auto-Generate Settings Dialog */}
      <Dialog open={showAutoGenerateDialog} onOpenChange={setShowAutoGenerateDialog}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Sparkles className="h-5 w-5 text-primary" />
              Автоматическая генерация постов
            </DialogTitle>
          </DialogHeader>
          <div className="space-y-5 pt-2">
            {/* Post Count */}
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <label className="text-sm font-medium text-foreground">Количество постов</label>
                <span className="text-sm font-bold text-primary">{autoGenerateSettings.postCount}</span>
              </div>
              <Slider
                value={[autoGenerateSettings.postCount]}
                onValueChange={([v]) => setAutoGenerateSettings(prev => ({ ...prev, postCount: v }))}
                min={1}
                max={10}
                step={1}
                className="w-full"
              />
              <div className="flex justify-between text-[10px] text-muted-foreground/60">
                <span>1 пост</span>
                <span>5 постов</span>
                <span>10 постов</span>
              </div>
            </div>

            {/* Sentence Range */}
            <div className="space-y-3">
              <label className="text-sm font-medium text-foreground">Диапазон предложений в посте</label>
              <div className="flex items-center gap-3">
                <div className="flex-1 space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="text-xs text-muted-foreground">От</span>
                    <span className="text-sm font-bold text-foreground">{autoGenerateSettings.minSentences}</span>
                  </div>
                  <Slider
                    value={[autoGenerateSettings.minSentences]}
                    onValueChange={([v]) => setAutoGenerateSettings(prev => ({ 
                      ...prev, 
                      minSentences: Math.min(v, prev.maxSentences - 1) 
                    }))}
                    min={1}
                    max={15}
                    step={1}
                    className="w-full"
                  />
                </div>
                <span className="text-xs text-muted-foreground">—</span>
                <div className="flex-1 space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="text-xs text-muted-foreground">До</span>
                    <span className="text-sm font-bold text-foreground">{autoGenerateSettings.maxSentences}</span>
                  </div>
                  <Slider
                    value={[autoGenerateSettings.maxSentences]}
                    onValueChange={([v]) => setAutoGenerateSettings(prev => ({ 
                      ...prev, 
                      maxSentences: Math.max(v, prev.minSentences + 1) 
                    }))}
                    min={2}
                    max={20}
                    step={1}
                    className="w-full"
                  />
                </div>
              </div>
              <p className="text-xs text-muted-foreground">
                Каждый пост будет содержать от {autoGenerateSettings.minSentences} до {autoGenerateSettings.maxSentences} предложений
              </p>
            </div>

            {/* Info */}
            <div className="rounded-lg bg-primary/5 border border-primary/20 p-3 space-y-1.5">
<p className="text-xs text-foreground font-medium">ℹ️ Процесс генерации (6 шагов):</p>
              <ul className="text-xs text-muted-foreground space-y-1 pl-4">
                <li className="list-disc"><strong>Шаг 1:</strong> Web research — поиск САМЫХ обсуждаемых новостей за 48ч</li>
                <li className="list-disc"><strong>Шаг 2:</strong> Сбор новостных статей по каждой теме</li>
                <li className="list-disc"><strong>Шаг 3:</strong> Поиск 5 самых обсуждаемых постов в X (Twitter)</li>
                <li className="list-disc"><strong>Шаг 4:</strong> Подсчёт <strong>РЕАЛЬНОЙ</strong> статистики с найденных постов</li>
                <li className="list-disc"><strong>Шаг 5:</strong> Написание постов от лица Sarah Icelyn</li>
                <li className="list-disc"><strong>Шаг 6:</strong> Перевод на русский + создание описания темы</li>
              </ul>
              <p className="text-[10px] text-muted-foreground/70 mt-2 pt-2 border-t border-primary/10">
                ✅ Статистика 100% реальная (с 5 найденных постов).<br/>
                � Ссылки получены через web_search инструмент Grok.<br/>
                ⚠️ Проверьте ссылки вручную перед публикацией.
              </p>
            </div>

            {/* Action buttons */}
            <div className="flex gap-3 pt-2">
              <Button
                variant="outline"
                onClick={() => setShowAutoGenerateDialog(false)}
                className="flex-1"
              >
                Отмена
              </Button>
              <Button
                onClick={handleAutoGenerate}
                className="flex-1 bg-primary hover:bg-primary/90"
              >
                <Sparkles className="h-4 w-4 mr-2" />
                Сгенерировать
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>

      {/* Auto-Generate Progress */}
      {isAutoGenerating && (
        <div className="rounded-xl border border-primary/20 bg-primary/5 px-4 py-3 flex items-center gap-3">
          <RefreshCw className="h-4 w-4 animate-spin text-primary shrink-0" />
          <span className="text-sm font-medium text-foreground">
            Генерирую {autoGenerateSettings.postCount} {autoGenerateSettings.postCount === 1 ? 'пост' : 'постов'}...
          </span>
        </div>
      )}

      {/* Auto-Generated Posts Table */}
      {autoGeneratedPosts.length > 0 && (
        <div className="rounded-xl border border-border bg-card overflow-hidden">
          <div className="px-4 py-3 border-b border-border/50 flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Sparkles className="h-4 w-4 text-primary" />
              <span className="text-sm font-semibold text-foreground">Автоматически сгенерированные посты</span>
              <span className="text-xs text-muted-foreground">({autoGeneratedPosts.length})</span>
            </div>
            <Button
              variant="outline"
              size="sm"
              onClick={() => setAutoGeneratedPosts([])}
              className="h-7 text-xs"
            >
              Очистить
            </Button>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead className="bg-secondary/30 border-b border-border/50">
<tr>
                  <th className="px-4 py-2 text-left text-xs font-semibold text-foreground">#</th>
                  <th className="px-4 py-2 text-left text-xs font-semibold text-foreground min-w-[150px]">Тема</th>
                  <th className="px-4 py-2 text-left text-xs font-semibold text-foreground min-w-[250px]">Описание</th>
                  <th className="px-4 py-2 text-left text-xs font-semibold text-foreground min-w-[130px]">
                    <div className="flex items-center gap-1.5">
                      <span>Статистика</span>
                      <div className="group relative">
                        <svg className="w-3.5 h-3.5 text-muted-foreground cursor-help" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                        </svg>
                        <div className="invisible group-hover:visible absolute z-50 left-0 top-6 w-72 p-3 bg-popover border border-border rounded-lg shadow-xl text-[10px] leading-relaxed">
                          <p className="font-semibold text-foreground mb-2">📊 Объяснение метрик:</p>
                          <div className="space-y-1.5 text-muted-foreground">
                            <p><span className="text-orange-400 font-semibold">🔥 Общий</span> — сумма комм. + ретв. с 5 постов</p>
                            <p><span className="text-blue-400 font-semibold">💬 Ср. комм.</span> — среднее комментариев на пост</p>
                            <p><span className="text-green-400 font-semibold">🔁 Ср. ретв.</span> — среднее ретвитов на пост</p>
                            <p><span className="text-yellow-400 font-semibold">⭐ Топ</span> — engagement самого обсуждаемого поста</p>
                            <p className="text-[9px] text-muted-foreground/60 mt-2 pt-1.5 border-t border-border">✅ Все данные реальные с найденных X постов</p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </th>
                  <th className="px-4 py-2 text-left text-xs font-semibold text-foreground min-w-[300px]">Пост от Sarah</th>
                  <th className="px-4 py-2 text-left text-xs font-semibold text-foreground min-w-[200px]">X (Twitter) посты</th>
                  <th className="px-4 py-2 text-left text-xs font-semibold text-foreground min-w-[200px]">Веб-ссылки</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border/50">
                {autoGeneratedPosts.map((post, i) => (
                  <tr key={i} className="hover:bg-secondary/20 transition-colors">
                    <td className="px-4 py-3 text-xs text-muted-foreground font-medium">{i + 1}</td>
                    <td className="px-4 py-3">
                      <div className="space-y-1">
                        <p className="text-sm font-medium text-foreground">{post.topicRu}</p>
                        <p className="text-[11px] text-muted-foreground/60 italic">{post.topicEn}</p>
                      </div>
                    </td>
                    <td className="px-4 py-3">
                      <p className="text-xs text-muted-foreground leading-relaxed">{post.summaryRu}</p>
                    </td>
                    <td className="px-4 py-3">
                      <div className="space-y-1.5 text-[11px]">
                        <div className="flex items-center gap-1.5">
                          <span className="text-muted-foreground">� Общий:</span>
                          <span className="font-bold text-orange-400">{post.stats?.totalEngagement?.toLocaleString() || 'N/A'}</span>
                        </div>
                        <div className="flex items-center gap-1.5">
                          <span className="text-muted-foreground">💬 Ср. комм.:</span>
                          <span className="font-semibold text-blue-400">{post.stats?.avgComments?.toLocaleString() || 'N/A'}</span>
                        </div>
                        <div className="flex items-center gap-1.5">
                          <span className="text-muted-foreground">🔁 Ср. ретв.:</span>
                          <span className="font-semibold text-green-400">{post.stats?.avgRetweets?.toLocaleString() || 'N/A'}</span>
                        </div>
                        <div className="flex items-center gap-1.5">
                          <span className="text-muted-foreground">⭐ Топ:</span>
                          <span className="font-semibold text-yellow-400">{post.stats?.topPostEngagement?.toLocaleString() || 'N/A'}</span>
                        </div>
                      </div>
                    </td>
                    <td className="px-4 py-3">
                      <div className="space-y-2">
                        <div className="flex items-start justify-between gap-2 mb-2">
                          <button
                            onClick={() => togglePostLanguage(i)}
                            className={cn(
                              "shrink-0 px-2 py-0.5 rounded text-[10px] font-bold transition-colors",
                              postLanguages[i] === 'ru' 
                                ? "bg-blue-500/20 text-blue-400 border border-blue-500/30"
                                : "bg-secondary/50 text-muted-foreground border border-border/50 hover:bg-secondary"
                            )}
                            title={postLanguages[i] === 'ru' ? 'Показать английский' : 'Показать русский'}
                          >
                            {postLanguages[i] === 'ru' ? '🇷🇺 RU' : 'EN'}
                          </button>
                        </div>
                        <p className="text-xs text-foreground leading-relaxed">
                          {postLanguages[i] === 'ru' ? post.postTextRu : post.postText}
                        </p>
                        <div className="flex gap-2">
                          <CopyButton 
                            text={postLanguages[i] === 'ru' ? post.postTextRu : post.postText} 
                            label="Копировать" 
                          />
                          <Button
                            onClick={() => handleVoicePost(i)}
                            variant="outline"
                            size="sm"
                            className="h-7 text-xs gap-1.5"
                          >
                            <Volume2 className="h-3 w-3" />
                            Озвучить
                          </Button>
                        </div>
                        
                        {/* Regeneration controls */}
                        <div className="mt-3 pt-3 border-t border-border/50 space-y-2">
                          <textarea
                            value={postFeedback[i] || ''}
                            onChange={(e) => setPostFeedback(prev => ({ ...prev, [i]: e.target.value }))}
                            placeholder="Пожелания по редактированию поста..."
                            className="w-full min-h-[60px] px-2.5 py-2 text-xs rounded-md bg-secondary/30 border border-border focus:border-primary focus:ring-1 focus:ring-primary/20 resize-none placeholder:text-muted-foreground/50"
                            disabled={regeneratingPosts[i]}
                          />
                          <Button
                            onClick={() => handleRegeneratePost(i)}
                            disabled={regeneratingPosts[i] || !postFeedback[i]?.trim()}
                            size="sm"
                            className="w-full h-7 text-xs gap-1.5"
                          >
                            {regeneratingPosts[i] ? (
                              <>
                                <RefreshCw className="h-3 w-3 animate-spin" />
                                Перегенерация...
                              </>
                            ) : (
                              <>
                                <RefreshCw className="h-3 w-3" />
                                Перегенерировать
                              </>
                            )}
                          </Button>
                        </div>
                      </div>
                    </td>
                    <td className="px-4 py-3">
                      <div className="space-y-1">
                        {post.xLinks.map((link, j) => (
                          <a
                            key={j}
                            href={link}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="flex items-center gap-1.5 text-[11px] text-primary hover:text-primary/80 transition-colors group"
                          >
                            <span className="shrink-0 font-bold leading-none">𝕏</span>
                            <span className="truncate group-hover:underline max-w-[150px]">{link.split('/').pop()}</span>
                          </a>
                        ))}
                      </div>
                    </td>
                    <td className="px-4 py-3">
                      <div className="space-y-1">
                        {post.webLinks.map((link, j) => {
                          let label = link
                          try { label = new URL(link).hostname.replace('www.', '') } catch { /* use raw */ }
                          return (
                            <a
                              key={j}
                              href={link}
                              target="_blank"
                              rel="noopener noreferrer"
                              className="flex items-center gap-1.5 text-[11px] text-primary hover:text-primary/80 transition-colors group"
                            >
                              <ExternalLink className="h-2.5 w-2.5 shrink-0" />
                              <span className="truncate group-hover:underline max-w-[150px]">{label}</span>
                            </a>
                          )
                        })}
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  )
}
